import 'dart:convert';
import 'dart:typed_data';
import 'package:pointycastle/export.dart';
import '../domain/license.dart';

/// Verifies the license signature fully offline using the public key.
/// Replace the placeholders with YOUR key (generated by the vendor signing tool).
/// Storing the key as modulus+exponent avoids ASN.1/PEM parsing in the client.
class LicenseVerifier {
  // TODO: paste your real RSA public key (decimal modulus).
  static final BigInt _modulus = BigInt.parse('REPLACE_WITH_DECIMAL_MODULUS');
  static final BigInt _exponent = BigInt.from(65537);

  bool verify(License lic) {
    try {
      final signer = RSASigner(SHA256Digest(), '0609608648016503040201')
        ..init(
          false,
          PublicKeyParameter<RSAPublicKey>(RSAPublicKey(_modulus, _exponent)),
        );
      final msg = Uint8List.fromList(utf8.encode(lic.canonicalPayload()));
      return signer.verifySignature(
        msg,
        RSASignature(base64.decode(lic.signature)),
      );
    } catch (_) {
      return false;
    }
  }
}
