import 'dart:convert';
import 'dart:typed_data';
import 'package:pointycastle/export.dart';
import '../domain/license.dart';

/// Verifies the license signature fully offline using the public key.
/// Replace the placeholders with YOUR key (generated by the vendor signing tool).
/// Storing the key as modulus+exponent avoids ASN.1/PEM parsing in the client.
class LicenseVerifier {
  // TODO: paste your real RSA public key (decimal modulus).
  static final BigInt _modulus = BigInt.parse(
    '20203797802593410663666366605079726360446927517292465263038419473866385984552141653206975007947126635288365632671500157384688728264457913161178253893157020185642329615433788401151707821940917520635932357988845312625187930062869261825677628121135819704504493375734464481970595446094463685971404638191659129129234720907927793258477069629325093169814196586347269275251249049476621222023504951393653382379485127722644266816581298524833794103812038512060073333917814610602502112878171236299217959477204264801178020594411625303937409306315774386458173443441490044507604407663411432931174876301534245877353262712707559573323',
  );
  static final BigInt _exponent = BigInt.from(65537);

  bool verify(License lic) {
    try {
      final signer = RSASigner(SHA256Digest(), '0609608648016503040201')
        ..init(
          false,
          PublicKeyParameter<RSAPublicKey>(RSAPublicKey(_modulus, _exponent)),
        );
      final msg = Uint8List.fromList(utf8.encode(lic.canonicalPayload()));
      return signer.verifySignature(
        msg,
        RSASignature(base64.decode(lic.signature)),
      );
    } catch (_) {
      return false;
    }
  }
}
